import React, { useState, useRef, useEffect } from 'react';
import { generateImage, buildPrompt, hasApiKey, getReferenceImage, getPromptTemplate } from '../services/dashscopeService';

const AIIconGenerator = ({ description, style, region, onSettingsClick }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [progress, setProgress] = useState(null);
  const [generatedImageUrl, setGeneratedImageUrl] = useState(null);
  const [error, setError] = useState(null);
  const [uploadedRefImage, setUploadedRefImage] = useState(null);
  const [refImageBase64, setRefImageBase64] = useState(null);
  const [isEditingPrompt, setIsEditingPrompt] = useState(false);
  const [editedPrompt, setEditedPrompt] = useState('');
  const abortControllerRef = useRef(null);
  const fileInputRef = useRef(null);

  const autoGeneratedPrompt = buildPrompt(description, style, region);

  // 从 localStorage 恢复上传的参考图
  useEffect(() => {
    const savedRefImage = localStorage.getItem('uploadedRefImage');
    const savedRefImageBase64 = localStorage.getItem('refImageBase64');
    if (savedRefImage && savedRefImageBase64) {
      setUploadedRefImage(savedRefImage);
      setRefImageBase64(savedRefImageBase64);
    }
  }, []);

  // 风格默认参考图 + 用户上传参考图
  const styleRefImage = getReferenceImage(style);
  const promptTemplate = getPromptTemplate(style);
  const displayRefImage = uploadedRefImage || styleRefImage;
  const isPromptModified = editedPrompt !== autoGeneratedPrompt;

  useEffect(() => {
    if (!isEditingPrompt) {
      setEditedPrompt(autoGeneratedPrompt);
    }
  }, [autoGeneratedPrompt, isEditingPrompt]);

  const handlePromptClick = () => {
    setEditedPrompt(autoGeneratedPrompt);
    setIsEditingPrompt(true);
  };

  const handlePromptSave = () => setIsEditingPrompt(false);
  const handlePromptCancel = () => {
    setEditedPrompt(autoGeneratedPrompt);
    setIsEditingPrompt(false);
  };
  const handlePromptReset = () => setEditedPrompt(autoGeneratedPrompt);

  const compressAndConvertToBase64 = (file, maxWidth = 512, maxHeight = 512, quality = 0.8) => {
    return new Promise((resolve, reject) => {
      const img = new Image();
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      img.onload = () => {
        let width = img.width;
        let height = img.height;
        if (width > maxWidth || height > maxHeight) {
          const ratio = Math.min(maxWidth / width, maxHeight / height);
          width = Math.floor(width * ratio);
          height = Math.floor(height * ratio);
        }
        canvas.width = width;
        canvas.height = height;
        ctx.drawImage(img, 0, 0, width, height);
        const base64 = canvas.toDataURL('image/jpeg', quality);
        resolve(base64);
      };
      img.onerror = reject;
      img.src = URL.createObjectURL(file);
    });
  };

  const handleRefImageUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;
    try {
      const base64 = await compressAndConvertToBase64(file);
      const imageUrl = URL.createObjectURL(file);
      setRefImageBase64(base64);
      setUploadedRefImage(imageUrl);
      // 持久化保存到 localStorage
      localStorage.setItem('uploadedRefImage', imageUrl);
      localStorage.setItem('refImageBase64', base64);
      setError(null);
    } catch (err) {
      console.error('图片上传失败:', err);
      setError('图片上传失败');
    }
  };

  const handleGenerate = async () => {
    if (!description.trim()) {
      setError('请输入图标描述');
      return;
    }
    if (!hasApiKey()) {
      setError('请先配置API Key');
      onSettingsClick?.();
      return;
    }

    setIsGenerating(true);
    setError(null);
    setGeneratedImageUrl(null);
    setProgress({ stage: 'starting', message: '准备生成...' });

    try {
      const prompt = editedPrompt || autoGeneratedPrompt;
      console.log('生成Prompt:', prompt);
      setProgress({ stage: 'creating', message: '创建任务中...' });

      // 如果没有用户上传的参考图，使用风格默认参考图
      let finalRefImageBase64 = refImageBase64;
      if (!finalRefImageBase64 && styleRefImage) {
        setProgress({ stage: 'creating', message: '加载参考图...' });
        finalRefImageBase64 = await fetch(styleRefImage)
          .then(res => res.blob())
          .then(blob => new Promise((resolve) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result);
            reader.readAsDataURL(blob);
          }));
        console.log('已加载风格默认参考图');
      }

      const result = await generateImage(prompt, (p) => {
        if (p.status === 'RUNNING') {
          setProgress({
            stage: 'generating',
            message: `生成中... (${p.attempts}/${p.maxAttempts})`,
            attempts: p.attempts,
            maxAttempts: p.maxAttempts
          });
        }
      }, { style, refImageBase64: finalRefImageBase64 });

      setGeneratedImageUrl(result.imageUrl);
      setProgress({ stage: 'done', message: '生成完成！' });
    } catch (err) {
      console.error('生成失败:', err);
      setError(err.message || '生成失败，请重试');
      setProgress(null);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleStop = () => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
    }
    setIsGenerating(false);
    setProgress(null);
    setError('已取消');
  };

  const handleDownload = async () => {
    if (!generatedImageUrl) return;
    try {
      const response = await fetch(generatedImageUrl);
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${description || 'icon'}-${style}.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('下载失败:', err);
    }
  };

  const handleConvertToSVG = () => {
    alert('PNG转SVG功能开发中...\n\n推荐工具：\n- convertio.co/png-svg\n- autotracer.org');
  };

  return (
    <div>
      <div className="section-label">
        <svg className="w-5 h-5 text-violet-500" fill="currentColor" viewBox="0 0 20 20">
          <path d="M13 7H7v6h6V7z" />
          <path fillRule="evenodd" d="M7 2a1 1 0 012 0v1h2V2a1 1 0 112 0v1h2a2 2 0 012 2v2h1a1 1 0 110 2h-1v2h1a1 1 0 110 2h-1v2a2 2 0 01-2 2h-2v1a1 1 0 11-2 0v-1H9v1a1 1 0 11-2 0v-1H5a2 2 0 01-2-2v-2H2a1 1 0 110-2h1V9H2a1 1 0 010-2h1V5a2 2 0 012-2h2V2zM5 5h10v10H5V5z" clipRule="evenodd" />
        </svg>
        AI 生成 / AI Generate
      </div>

      {/* Reference Image */}
      <div className="mb-5">
        <div className="flex items-center justify-between mb-2">
          <span className="text-sm text-clay-muted">参考图（可选）</span>
          <button
            onClick={() => fileInputRef.current?.click()}
            className="text-sm font-semibold text-violet-500 hover:text-violet-600 transition-colors"
            style={{ fontFamily: 'Nunito, sans-serif' }}
          >
            {uploadedRefImage ? '更换' : '上传'}
          </button>
          <input
            ref={fileInputRef}
            type="file"
            accept="image/*"
            onChange={handleRefImageUpload}
            className="hidden"
          />
        </div>
        <div className="w-20 h-20 rounded-[20px] bg-[#EFEBF5] flex items-center justify-center overflow-hidden"
          style={{ boxShadow: 'inset 4px 4px 8px #d9d4e3, inset -4px -4px 8px #ffffff' }}>
          {displayRefImage ? (
            <img src={displayRefImage} alt="参考" className="max-w-full max-h-full object-contain" />
          ) : (
            <svg className="w-8 h-8 text-clay-muted/50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
          )}
        </div>
        {uploadedRefImage && (
          <button
            onClick={() => {
              setUploadedRefImage(null);
              setRefImageBase64(null);
              localStorage.removeItem('uploadedRefImage');
              localStorage.removeItem('refImageBase64');
            }}
            className="mt-2 text-sm text-pink-500 hover:text-pink-600 transition-colors font-medium"
          >
            清除参考图
          </button>
        )}
      </div>

      {/* Editable Prompt */}
      {description && promptTemplate && (
        <div className="mb-5">
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm text-clay-muted">
              Prompt {isPromptModified && <span className="text-pink-500">(已修改)</span>}
            </span>
            {!isEditingPrompt ? (
              <button onClick={handlePromptClick} className="text-sm font-semibold text-violet-500 hover:text-violet-600 transition-colors">编辑</button>
            ) : (
              <div className="flex gap-3">
                <button onClick={handlePromptReset} className="text-sm text-clay-muted hover:text-clay-foreground">重置</button>
                <button onClick={handlePromptCancel} className="text-sm text-clay-muted hover:text-clay-foreground">取消</button>
                <button onClick={handlePromptSave} className="text-sm font-semibold text-violet-500">保存</button>
              </div>
            )}
          </div>
          {isEditingPrompt ? (
            <textarea
              value={editedPrompt}
              onChange={(e) => setEditedPrompt(e.target.value)}
              className="clay-input resize-none"
              rows={4}
            />
          ) : (
            <div
              onClick={handlePromptClick}
              className="p-4 text-sm rounded-[20px] cursor-pointer transition-all hover:bg-[#EFEBF5]"
              style={{
                background: 'rgba(239, 235, 245, 0.5)',
                boxShadow: 'inset 3px 3px 6px #d9d4e3, inset -3px -3px 6px #ffffff'
              }}
            >
              {editedPrompt || autoGeneratedPrompt}
            </div>
          )}
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="mb-5 p-4 rounded-[20px] bg-pink-50 text-pink-600 text-sm font-medium"
          style={{ boxShadow: 'inset 3px 3px 6px rgba(236, 72, 153, 0.1)' }}>
          {error}
        </div>
      )}

      {/* Buttons */}
      <div className="flex gap-3">
        <button
          onClick={handleGenerate}
          disabled={isGenerating || !description.trim()}
          className={`
            flex-1 h-14 rounded-[20px]
            ${isGenerating || !description.trim()
              ? 'bg-gray-200 text-gray-400 cursor-not-allowed'
              : 'clay-button'
            }
          `}
          style={{ fontFamily: 'Nunito, sans-serif' }}
        >
          {isGenerating ? (
            <span className="flex items-center gap-2">
              <svg className="w-5 h-5 animate-spin" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              生成中...
            </span>
          ) : (
            '生成图标'
          )}
        </button>
        {isGenerating && (
          <button
            onClick={handleStop}
            className="clay-button clay-button-secondary px-6"
            style={{ fontFamily: 'Nunito, sans-serif' }}
          >
            停止
          </button>
        )}
      </div>

      {/* Progress */}
      {progress && isGenerating && (
        <div className="mt-5">
          <div className="flex items-center gap-3 text-sm text-clay-muted">
            <div className="w-3 h-3 rounded-full animate-pulse"
              style={{
                background: 'linear-gradient(to bottom right, #A78BFA, #7C3AED)',
                boxShadow: '2px 2px 4px rgba(139, 92, 246, 0.3)'
              }} />
            {progress.message}
          </div>
          {progress.attempts && (
            <div className="mt-3 clay-progress">
              <div
                className="clay-progress-fill"
                style={{ width: `${(progress.attempts / progress.maxAttempts) * 100}%` }}
              />
            </div>
          )}
        </div>
      )}

      {/* Generated Image */}
      {generatedImageUrl && (
        <div className="mt-6">
          <div className="rounded-[20px] p-6"
            style={{
              background: 'rgba(239, 235, 245, 0.5)',
              boxShadow: 'inset 4px 4px 8px #d9d4e3, inset -4px -4px 8px #ffffff'
            }}>
            <img
              src={generatedImageUrl}
              alt="生成的图标"
              className="max-w-[150px] max-h-[150px] mx-auto object-contain rounded-xl"
            />
          </div>
          <div className="mt-4 flex gap-3">
            <button
              onClick={handleDownload}
              className="flex-1 clay-button text-sm"
              style={{ fontFamily: 'Nunito, sans-serif' }}
            >
              下载 PNG
            </button>
            <button
              onClick={handleConvertToSVG}
              className="flex-1 clay-button clay-button-secondary text-sm"
              style={{ fontFamily: 'Nunito, sans-serif' }}
            >
              转 SVG
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default AIIconGenerator;
